name: Continuous Deployment

# When action will run
on: push

jobs:
  # single job called "build and deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
    
      # Logs the completed deployment
      - name: Post-deployment
        run: echo Build completed on `date`
