name: Continuous Integration Pipeline

# When action will run
on: push

jobs:
  # single job called "build and test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out project
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          make install
      
      - name: Lint with pylint
        run: |
          make lint

      # Logs the completed deployment
      - name: Log successful build
        run: echo Build completed on `date`
